name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ sectrets.SEC }}
        issue-message: "Thanks! first issue"
        pr-message: "Thanks too first pull request"
